topics = [phrase.lower().strip() for phrase in [
    "Politics and Political Events",
    "International Relations",
    "Immigration and Border Security",
    "Trade and Tariffs",
    "Economy and Jobs",
    "Healthcare",
    "COVID-19 Pandemic",
    "China",
    "Iran",
    "North Korea",
    "Russia",
    "Middle East Conflict",
    "Climate Change",
    "Environment and Energy",
    "Gun Control",
    "Tax Reform",
    "Foreign Policy",
    "National Security",
    "Military",
    "Law and Order",
    "Supreme Court",
    "2020 Presidential Election",
    "Voter Fraud",
    "Fake News",
    "Media and Press",
    "Social Media",
    "Big Tech",
    "Impeachment",
    "Congress",
    "Executive Orders",
    "Stock Market",
    "Infrastructure",
    "2nd Amendment",
    "Religious Freedom",
    "Racial Issues",
    "LGBT Rights",
    "Women's Rights",
    "Veterans Affairs",
    "Education",
    "Space Exploration",
    "Immigration Reform",
    "NATO",
    "United Nations",
    "Tax Cuts",
    "Israel",
    "Saudi Arabia",
    "National Anthem Protests",
    "Federal Reserve",
    "The Wall (Border Wall)",
    "International Trade Deals",
    "Social Security",
    "Opioid Crisis",
    "Federal Budget",
    "Healthcare Reform",
    "Twitter Censorship",
    "National Parks",
    "Puerto Rico",
    "Agriculture and Farming",
    "9/11 Anniversary",
    "Hurricane Response",
    "Criminal Justice Reform",
    "American History",
    "The Economy",
    "Space Force",
    "4th of July Celebrations",
    "Thanksgiving and Christmas Greetings",
    "Awards and Honors",
    "Personal Feuds and Criticisms",
    "Business Ventures and Promotions",
    "Pop Culture References"
]]